### PR TITLE
Magick.NET-Q8-AnyCPU Package update

### PR DESCRIPTION
**Pull request by SemionMcAlice**
updated Nuget Package "Magick.NET-Q8-AnyCPU" from 7.19.0.1 to 7.21.1
made changes in the ZXing.Magick project to return IMagickImage<byte> instead of the generic IMagickImage.

### CODE REVIEW

**Comment by micjahn** [comment]
Thanks for the PR.
One question: why did you change the type IMagickImage to IMagickImage<byte>?
If I look to the latest commit in the Magick.NET repo (https://github.com/dlemstra/Magick.NET/commit/323e3ff75e1fdfbef2762205bfc2ffa2b425d64b) I find the other way. Some method are changed from IMagickImage<QuantumType> to IMagickImage.

**Comment by SemionMcAlice** [comment]
Hey,
my first instinct was to just leave the IMagickImage as the type.
but since the method ....Image.Create(totalBuffer) _(file: MagickImageRenderer.cs, line: 109)_ returns a IMagickImage<byte> object, i thought it's better to return it all the way, to know what exact type is return when using the library.

**Comment by SemionMcAlice** [comment]
should i change it back to `IMagickImage`

**Comment by micjahn** [comment]
Not yet. I have to think about it. Perhaps your are right

________________________________
Von: Semion Mc Alice <notifications@github.com>
Gesendet: Wednesday, August 12, 2020 2:58:31 PM
An: micjahn/ZXing.Net <ZXing.Net@noreply.github.com>
Cc: Michael Jahn <mikej06@hotmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [micjahn/ZXing.Net] Magick.NET-Q8-AnyCPU Package update (#270)


should i change it back to IMagickImage

**Comment by micjahn** [comment]
I think, you are right. The renderer and writer classes should be more specific. That makes sense.
Thanks!

**Pull request merged**
