### PR TITLE
Narrow scanning area

### PR DESCRIPTION
**Pull request by michcons**
Sometimes when scanning 1D images you want to use barcode line in your app that will indicate where the scanning is done (for example you have 3 closely located barcodes and you want to be precise which barcode you are scanning). 

This PR touches only vertical narrowing of scanning area (quite common scenario that you want to use full width but not full height of image).

### CODE REVIEW

**Comment by micjahn** [comment]
Thanks for the PR.
If I understand it the right way you want to introduce a new decoding hint which reduces the scanning process only to a small vertical area. Right?
Why not cropping the image before passing it to the Decode method? Or why not using a custom implementation of a LuminanceSource which can do the same?
In my opinion it is more straight forward to crop the image to only the needed barcode area. Normally that would additionally speed up the decoding process.

**Comment by michcons** [comment]
Yes, that's exactly what I want to do. Because I am using ZXing.Net.Mobile I thought that it will be easier to use additional decoding hint instead of creating custom LuminaceSource for each and every platform (more people might find this feature useful while doing less work in the future).

**Comment by michcons** [comment]
I've started implementing the custom luminance sources today and I realised, that because of cropping process on the image I will be unable to scan QR codes at the same time, which is also nice-to-have feature (allow to narrow 1D and scan for 2D in bigger area/whole screen).

If you disagree please let me know so I can close this PR and create one with custom luminance sources in ZXing.Net.Mobile repo :) Thanks!

**Comment by micjahn** [comment]
Sorry, I really don't get it.
Cropping a bitmap to a specific area is a no brainer. Additionally, it speeds up the decoding process at all because the grayscale conversion and the binarizer have to process a smaller image. I don't want to introduce a new decoding hint while there is a much better solution in my opinion. And I'm not sure if it is a good idea to use different scanning areas for 1d and 2d codes. Most of the scanner apps are showing a rectangle around the scanning area. The user can't recognize that the app uses different areas.

**Comment by michcons** [comment]
Ok, thank you for your input :) 

I am closing this pull request :)

Stay safe!

**Pull request closed without merging**
