### PR TITLE
Skia barcode performance

### PR DESCRIPTION
**Pull request by ghost1face**
* Reduce allocations and overall processing time

Here's a few more benchmarks to compare to GDI and the current implementation of the `ZXing.SkiaSharp.BarcodeReder` on the `master` branch:

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.14393.3384 (1607/AnniversaryUpdate/Redstone1)
Intel Xeon CPU E5-2686 v4 2.30GHz, 1 CPU, 4 logical and 4 physical cores
  [Host]     : .NET Framework 4.7.2 (4.7.3468.0), X86 LegacyJIT
  DefaultJob : .NET Framework 4.7.2 (4.7.3468.0), X86 LegacyJIT


```
|      Method |                 File |      Mean |     Error |    StdDev |    Median | Rank |    Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|------------ |--------------------- |----------:|----------:|----------:|----------:|-----:|---------:|---------:|---------:|-----------:|
|  GDIScanner | D:\Us(...)5.png [80] |  5.680 ms | 0.0390 ms | 0.0345 ms |  5.670 ms |    1 |  85.9375 |  85.9375 |  85.9375 |  308.02 KB |
|   Optimized | D:\Us(...)5.png [80] |  8.772 ms | 0.1727 ms | 0.2739 ms |  8.575 ms |    2 |  78.1250 |  78.1250 |  78.1250 |  305.89 KB |
| SkiaScanner | D:\Us(...)5.png [80] | 11.779 ms | 0.0453 ms | 0.0424 ms | 11.790 ms |    3 | 328.1250 | 328.1250 | 328.1250 | 1507.34 KB |

|      Method |                 File |      Mean |     Error |    StdDev | Rank |    Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|------------ |--------------------- |----------:|----------:|----------:|-----:|---------:|---------:|---------:|-----------:|
|  GDIScanner | D:\Us(...)7.png [80] |  5.508 ms | 0.0286 ms | 0.0253 ms |    1 |  85.9375 |  85.9375 |  85.9375 |  308.02 KB |
|   Optimized | D:\Us(...)7.png [80] |  8.320 ms | 0.0178 ms | 0.0149 ms |    2 |  78.1250 |  78.1250 |  78.1250 |  305.89 KB |
| SkiaScanner | D:\Us(...)7.png [80] | 11.529 ms | 0.0493 ms | 0.0461 ms |    3 | 328.1250 | 328.1250 | 328.1250 | 1507.41 KB |

This last case was surprising, GDI+ was the slowest of all, the Optimized version still had far less allocations however.

|      Method |                 File |     Mean |     Error |    StdDev | Rank |     Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|------------ |--------------------- |---------:|----------:|----------:|-----:|----------:|---------:|---------:|-----------:|
| SkiaScanner | D:\Us(...)3.png [79] | 1.721 ms | 0.0445 ms | 0.0653 ms |    1 |  123.0469 | 123.0469 | 123.0469 |  423.93 KB |
|   Optimized | D:\Us(...)3.png [79] | 2.828 ms | 0.0136 ms | 0.0127 ms |    2 |   23.4375 |  23.4375 |  23.4375 |   89.45 KB |
|  GDIScanner | D:\Us(...)3.png [79] | 3.793 ms | 0.0463 ms | 0.0433 ms |    3 | 1011.7188 |  50.7813 |  23.4375 | 5273.41 KB |

The main thing to note here is we are almost as fast as the GDI+ implementation and less allocations overall.

Looking through the library there doesn't seem to be any unit tests for the Skia implementation and I am more than happy to put them together.  Do you have any preference on where they should live?

### CODE REVIEW

**Comment by micjahn** [comment]
Sorry, I didn't have enough time to look at your changes yet.
Is there any chance to replace the following line to prevent the allocations?
SKColor pixel = new SKColor(colorVal);

**Comment by ghost1face** [comment]
`SKColor` is a struct so just simple value types, the benefit here is that depending on the color type, the Red and Blue values can be in different positions:

```
RGBA
BGRA
```

The `SKColor` struct helps simplify that logic which, IMHO, is a benefit here.  The major change was to avoid allocating a contiguous block of memory by accessing the `Pixels` property of the image.  Instead, just keep it in the unmanaged space and read small pieces of it.

If you have other suggestions for optimizations, I'm all for it.  But I think we are definitely on the right track in making this perform much better in regards to CPU/Memory!

**Comment by micjahn** [comment]
First, I forgot to say: "Thank you for your efforts."

As far as I understand the struct SKColor it doesn't know anything about the difference between RGBA and BGRA.
The constructor is the following:
	`public SKColor(uint value)
	{
		color = value;
	}`
And the color components are hard coded like the following:
	`public byte Red => (byte)(color >> 16 & 0xFF);`

Perhaps you should double-check it. Maybe I'm wrong.

I'm not sure if the current C# compiler does a perfect job optimizing loops. If not, then it could be possible that the following micro-optimization can save some CPU-cycles:

                    for (int row = 0; row < height; row++)
                    {
                        for (int col = 0; col < width; col++)
                        {
                            var index = width * row + col;
                            ...
change to

                    for (int row = 0; row < height; row++)
                    {
                        var index = width * row;
                        for (int col = 0; col < width; col++, index++)
                        {
                        ...

**Comment by ghost1face** [comment]
@micjahn you are correct, I think I got caught up in the documentation and my previous commit.  

https://github.com/micjahn/ZXing.Net/pull/230/commits/75f554066b9ccca8954b9612fdeaaac097874a1c#diff-9b0dd2bed16901c4bdc69466ae3a9e25R96

I removed the `SKColor` usage and just applied the shifting ourselves, not much of a performance gain there, but happy to make the change. 

I also applied the loop optimization which does have some impact, I'd imagine the impact would be more noticeable if dealing with larger images.  Thanks for calling that out!

Lastly I did notice that some of the images in your unit tests are `Index8` color type.  As of `Skia 1.68` support of this color type was removed from Skia and SkiaSharp:

https://github.com/mono/SkiaSharp/issues/908

I'm wondering what we should do here, do we want to upgrade minimum supported version for this lib and update the `SkBitmapLuminanceSource` accordingly?

**Comment by micjahn** [comment]
I think I will build a new release with Skia < 1.68 which includes your changes. After that, the Index8 support has to be removed and a new version with Skia >= 1.68 should be built.

Unit tests: all bindings are currently not covered by unit tests. Shame on me. New tests should be inside a new project which should be located under Source/Bindings/Tests/ZXing.SkiaSharp in your case.

**Comment by ghost1face** [comment]
Perfect, I was thinking the same as far as project structure but didn't want to set it all up and you had different plans.  I'll go ahead and start getting those setup, either in this branch or a new branch/pr if you prefer.

**Comment by micjahn** [comment]
You can use this branch because it belongs to your current changes.

**Comment by ghost1face** [comment]
Got unit tests up, unfortunately some don't seem to be passing.  I tested prior to the changes I've made to make sure they would still be failing tests prior.

I created a generic `AbstractBlackBoxTestCase<TBitmap>` class that provides two abstract methods:

```
protected abstract TBitmap rotateImage(TBitmap original, float degrees);

protected abstract TBitmap openFromFile(string filePath);
```

I then created `SkiaBarcodeBlackBoxTestCase` as the base class for all unit tests in this library.  I was thinking the best way to run these tests for all Bindings may be some scripting or templates that would generate each one of the blackbox cases implementing the binding specific test base class.

This may be a good work item for next phase to get all bindings under tests without too much work.  Take a look and tell me what you think.  Also, any help with the test cases would be great.

**Comment by micjahn** [comment]
In my opinion the copy of all test classes of the library as a separate test suite for skia sharp bindings doesn't make sense. It would be much better to have only some specific tests for the classes inside the binding project. Additional there should be a very small number of integration tests that are decoding a handful of images.
Please remove the copied tests and add only some specific tests. Thanks a lot!

**Comment by micjahn** [comment]
Now I found the time to look through the current changes of this PR.
Do you really think that it is necessary to keep a copy of all of the following test classes?
grafik
In my opinion the most important one is the class SKBitmapLuminanceSourceTests. It's the only one which should stay in the test project. What do you think?

**Comment by ghost1face** [comment]
Hey man, sorry haven't gotten around to finishing changes, I can close this in the meantime so it's not sitting here.  I should be able to get back to it in the next few days.

I agree the `SKBitmapLuminanceSource` is the main thing that's being tested and tests should be focused there.  However, all scanning is just about based on the `LuminanceSource` and so we potentially can have multiple barcode scanners using different implementations of `LuminanceSource`.  From the looks of it the SKBitmapLuminance source doesn't seem to be as accurate as the default one.

This leads me to believe that we should have a full integration test for all types of barcodes.  This is why originally I copied the tests into `ZXing.SkiaSharp`, the plan was to use this as a way to understand how it all works and potentially apply the integration tests for all implementations (A lot to tackle).

It's definitely a lot, but if we can potentially receive different results based on the Bitmap implementation behind the scenes, it may be a good idea to ensure all implementations are returning accurate results.

Let me know your thoughts here and I'll be happy to make any other changes, I should be getting some more time to focus on this in the next few days.

**Comment by micjahn** [comment]
The main problems are the time-consuming tests.
All barcode decoders are based on the luminance values. It should be absolutely ok if the tests only compare the resulting luminance values between two different implementations. That should save a lot of cpu cycles.

**Comment by ghost1face** [comment]
I'm back and have made requested changes, my tests to compare to the GDI+ (BitmapLuminanceSource) ensure the pixel value is within a margin of error +/- 3.  All tests pass for now, but I think this may be a good thing to check if even a 1 pixel difference causes the image to not be read properly hence causing barcode scanning differences.

For now, we are at least covered and should be able to detect anomalies going forward.  I chose a good range of images in the test suite here.  Let me know if there's anything else you'd like to do here.

**Comment by micjahn** [comment]
I published a new version of the package.

**Comment by micjahn** [comment]
Thanks for your work.

**Comment by micjahn** [comment]
Version 0.16.6 contains your changes and is build against SkiaSharp 1.60. And version 0.16.7 is build against SkiaSharp 1.68.1.1.

**Comment by ghost1face** [comment]
Perfect! Thanks alot for getting it published!

**Pull request merged**
